# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-02 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField()),
                ('patient_id', models.BigIntegerField()),
                ('next_status', models.TextField()),
                ('event_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientWaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('time_waiting', models.BigIntegerField()),
            ],
        ),
    ]
