# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientwaiting',
            name='appointment_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
