# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_patientwaiting_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientwaiting',
            name='doctor_id',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
